feat: catch hyper util errors (#268)
looking at this
https://console.cloud.google.com/logs/query;query=resource.type%3D%22k8s_container%22%0A-jsonPayload.message%3D%22scheduler.tick_scheduled%22%0Alabels.%22k8s-pod%2Fservice%22%3D%22uptime-checker%22%0A-%22DNS%22;summaryFields=:true:32:beginning;cursorTimestamp=2025-02-24T22:52:57.665242903Z;duration=PT15S?project=internal-sentry

we can see there are a lot of raw errors making it through. some of them
are these hyper_util errors. we need to pin the library from being a
sub-dependency so we can use the error here to cast it and return the
parsed error.

it looks like there are some ssl errors which can make it into this
category, so can follow up to try to separate those. specifically
```
check_url.error: reqwest::Error { kind: Request, source: hyper_util::client::legacy::Error(Connect, Ssl(Error { code: ErrorCode(5), cause: None }, X509VerifyResult { code: 0, error: "ok" })) }
```